id: I74235A86
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T20:30:42+00:00'
last_modified: '2022-06-07T18:00:33.942602+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20095
  title: དམྱལ་གླིང་མུན་པ་རང་གསལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9BAC:
      image_group_id: I1KG17305
      title: ''
      total_pages: 120
      order: 1
      base_file: 9BAC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
