id: P003162
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 10:44:25.884860
source_metadata:
  id: bdr:W20095
  title: དམྱལ་གླིང་མུན་པ་རང་གསལ།
  author: ''
  volumes:
    8b39ff4f330e454e94e2f01a2e7260eb:
      image_group_id: I1KG17305
      title: ''
      volume_number: 1
      total_pages: 120
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
